### PR TITLE
Add Version::__toString()

### PR DESCRIPTION
**Pull request by ostrolucky**
This will simplify DI configuration of packages which want to use this library

### CODE REVIEW

**Comment by Jean85** [comment]
Hello there, and thanks for the contribution!

I'm afraid that this modification could break some stuff somewhere, "thanks" to the implicit casting to string... Can you elaborate a little more on your use case, so I can understand it better?

**Comment by ostrolucky** [comment]
Can you elaborate how would this change break some stuff somewhere? This change isn't BC break in nature.

This change is to avoid to declare factory for `Version::getPrettyVersion`. I can instead inject `Version` right into `Application`. It's just something to make life little easier. This small package already requires 3 service definitions. I don't want to define 4 definitions for such a silly thing.

**Comment by Jean85** [comment]
So you are doing something like:
```php
new Application('appName', PrettyVersions::getVersion('your/app')->getPrettyVersion());
```
Right? But after your PR, your code should became:
```php
new Application('appName', (string)PrettyVersions::getVersion('your/app'));
```
So you basically traded a method call for a cast, and that's not pretty useful. Not doing the cast also can became dangerous, since you would have to rely on the fact that the `Application` class does it for you. And, i.e. with Symfony less than 4, that doesn't happen.

Yes, you're right, it's not BC but it's a behavior that could create a lot of BC fragility in the future IMO...

**Comment by ostrolucky** [comment]
Well yes, this is not very useful if you use it with explicit cast. Implicit casts are what I'm interested in. In use case I occured I could count with fact that Symfony 4 >= is used, but in most cases I believe it can be used with Application class Symfony < 4 too. 

Yes, it's a bit dangerous, since I rely on a fact typehint won't be removed or strict_types wouldn't be flipped on, but hey, it's calculated risk. Those things are not going to happen anytime soon.

Not sure I understand your last sentence. Do you mean it can create BC fragility for you as maintainer of this library, or application using it? 

If first, I don't see how. If there is a BC break by changing output of  `__toString()` method, that means `getPrettyVersion()` method has been changed itself, which is itself BC break.

If second, please don't do policing of applications using your library. I don't want you to advertise this method, or recommend it, I want it as a choice for people who deem it safe to use it and this choice will  stand on their shoulders. If they chose wrong and applications gets broken in future, they have only themselves to blame. 

I think this change fits well for your library, which is just slim convenience wrapper. So I want it to make just slightly more convenient.

**Comment by Jean85** [comment]
> Not sure I understand your last sentence. Do you mean it can create BC fragility for you as maintainer of this library, or application using it?

Yes, I meant for me as a maintainer.

I gave this an other thought, and I'll merge this. I'll release this later with a minor version bump, but I'll prefer to do it after updating the readme.

Thanks!

**Pull request merged**
