### PR TITLE
Fix handling of provided and replaced packages

### PR DESCRIPTION
**Pull request by Jean85**
This fixes the behavior under 1.4 with replaced and provided packages, as kindly pointed out by @seldaek in https://github.com/Jean85/pretty-package-versions/pull/15#discussion_r416431585.

@seldaek can you please review this?

### CODE REVIEW

**Comment by Seldaek** [comment]
This does not work. That's why we return null and suggest using `satisfies()` instead of relying on getVersion/... 

The problem is replace/provide is a version constraint, not a version number. So if you ask `satisfies($parser, 'foo/bar', '1.0.0')` it can check if the constraint  matches `1.0.0` and return true/false, but if you just want get the provided version like this PR does, you'll end up with stuff like `^1.0` as "version", which makes no sense, and will surely break people's code. 

There is just no way to build this in a compatible way to Marco's package's API, because it was broken and ignored providers/replacers (except for root replacers for some reason).

Getting a version is just not always a valid use case. It'll work if the package is installed normally, but really people should rather rely on satisfies if they want to know whether a given version number is present.

**Comment by Jean85** [comment]
The use case of this package is normally to show which version of a package is installed, rather if a specific version is present, so this case is more of an edge case.

I understand though what you're saying, I'm misusing the API that I'm exposing, since it would "lie" to the end user. I'll revert this PR partially, and throw an exception in those two cases, so the end user will not rely on those.

Thanks for the review.

**Comment by Seldaek** [comment]
Yes essentially if a package is replaced then things will break. IMO throwing when that happens isn't great either though as it means for example if I use a package vendor/a which relies on your package to call getVersion('foo/b'), then I decide to replace package foo/b with something else, suddenly I get exceptions at runtime from vendor/a.. and I can not do anything about it.

IMO the only correct way to handle this is to deprecate these APIs as they do not offer a complete solution. Up to you though.

**Comment by Jean85** [comment]
That's kinda what I want to do: my idea is to avoid releasing a 2.0 and suggest using Composer instead anyway. 

What I'm trying to achieve is to maintain something kinda compatible inside 1.x of this package, so that users are able to obtain a semi-stable API without locking onto Composer 2 for the near future.

Bottom line though, I never intended this package to provide a "pretty version" (as in Composer) that is always usable with i.e. `version_compare`, but instead something "fancy" to be displayed, like in our main dependant, PHPStan: https://github.com/phpstan/phpstan-src/blob/9c56b393782a074b13d21d3d886eb2767f036884/bin/phpstan#L63-L73

So, I think I'll prefer leaving the API as it is, giving some unreliable information in case of replaced or provided packages (which is still better than crapping out with a fatal), and suggesting the migration to Composer 2 native API if that kind of reliable information is needed.

/cc @ondrejmirtes which is probably interested; can you weigh in on why you needed to catch that `\OutOfBoundException` in PHPStan? Probably while replacing PHPStan with the shim? Would this PR break something for you?

**Comment by Seldaek** [comment]
I see, yes that's completely fine. For self-introspection like phpstan looking to show its own version, IMO it's fine to use getVersion as if it returns null it's the fault of a replacer, but it's also in the hands of the replacer to fix the code in their fork so it introspects with the replacer's package name.

**Comment by ondrejmirtes** [comment]
@Jean85 About `OutOfBoundException` - I'm not sure, but it definitely happened to me. In which situation does this package throw this exception? I'm thinking it might be some situation when the user runs `composer install --no-plugins`. Which is no longer a problem because PHPStan ships as a single PHAR and this information is already baked in.

Also, PHPStan no longer `replace`s anything in its composer.json.

**Comment by Jean85** [comment]
@ondrejmirtes yes it happened with `--no-plugins` or `--no-scripts`, but it was Ocramius' underlying dependency that was throwing.

Since the edge case (replaced or provided packages) is not used, and we were throwing an exception before, I would prefer to rewrite this PR and throw as before.

If someone wants a more stable API, Composer 2 (or custom exception wrapping) would be the path to follow.

**Pull request closed without merging**
