### PR TITLE
Fixed type hint error when the package's pretty_version is null.

### LINKED ISSUE #24: Prettify "No version set"
When Composer can not determine the version of a package, it sets it to `No version set (parsed as 1.0.0)@`.
(For example, this happens for the root package if we are not in a Git repository.)

Maybe `PrettyVersions` could return something more user-friendly like `null` or "unknown"?

### PR DESCRIPTION
**Pull request by limingxinleo**
fix https://github.com/Jean85/pretty-package-versions/issues/24

### CODE REVIEW

**Comment by limingxinleo** [comment]
`InstalledVersions::getPrettyVersion` and `InstalledVersions::getReference` will be return null sometimes.

**Comment by limingxinleo** [comment]
Could you please take a look ?

Thanks

**Comment by Jean85** [comment]
Thank you for this PR, I was looking into this same issue because I was getting CI failures in https://github.com/getsentry/sentry-php/pull/1170

While debugging there, I've found that the issue that caused that was the fact that I was asking for the version of a replaced package; so, returning a version there doesn't make sense.

What's your use case here then? I see that You're splitting `||`, but that to me seems like you're working on a `composer.json` constraint, and not an exact version.

**Comment by Jean85** [comment]
This seems the same stuff that I tried tackling in #16...

**Comment by limingxinleo** [comment]
Sure, it is not an exact version.

It is a guess version.

**Comment by Jean85** [comment]
Not a guess, it's a constraint, see the excellent explanation by Jordi (Composer creator) in https://github.com/Jean85/pretty-package-versions/pull/16#issuecomment-620550459.

I'm closing this in favor of #31, which is my proposed solution for this issue.

**Comment by limingxinleo** [comment]
Ok

**Pull request closed without merging**
